aic_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from apps.intro import urls as intro_urls
from apps.accounts import urls as account_urls
from apps.game import urls as game_urls
from zinnia import urls as zinnia_urls
from apps.game import urls as game_urls
from apps.billing import urls as billing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(intro_urls)),

    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^accounts/', include(account_urls)),
    url(r'^blog/', include(zinnia_urls)),
    url(r'^game/', include(game_urls)),
    url(r'^articles/comments/', include('django_comments.urls')),
    url(r'^tinymce/filebrowser/', include('zinnia_tinymce.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^billing/', include(billing_urls))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts import views

app_name = "accounts"
urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^update_profile/$', views.UpdateProfileView.as_view(), name='update_profile'),
    url(r'^create_team/(?P<challenge_id>[0-9]+)$', views.create_team, name='create_team'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create_team/success_create_team$', views.success_create_team, name='success_create_team'),
    url(r'^panel/(?P<participation_id>[0-9]+)?$', views.team_management, name='panel'),
    url(r'^panel/accept_participation/(?P<participation_id>[0-9]+)$', views.accept_participation,
        name='accept_participation'),
    url(r'^panel/reject_participation/(?P<participation_id>[0-9]+)$', views.reject_participation,
        name='reject_participation'),
    url(r'^panel/cancel_participation/(?P<participation_id>[0-9]+)/(?P<user_id>[0-9]+)$',
        views.cancel_participation_request, name='cancel_participation_request'),
    url(r'^panel/add_participation/(?P<participation_id>[0-9]+)$', views.add_participation,
        name='add_participation'),
    url(r'^panel/set_final_submission/(?P<submission_id>[0-9]+)', views.set_final_submission,
        name='set final submission'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^email_sent$', views.email_sent, name='email_sent'),
    url(r'^email_confirm$', views.email_confirm, name='email_confirm'),
    url(r'^email_invalid$', views.email_invalid, name='email_invalid'),
    url(r'^challenge_a_team/(?P<participation_id>\d+)$', views.challenge_a_team, name='challenge_a_team'),

    url(r'^panel/submissions', views.submissions, name='panel_submissions'),
    url(r'^panel/team$', views.team_management, name='panel_team_management'),
    url(r'^panel/bhistory', views.battle_history, name='panel_battle_history'),
    url(r'^panel/teampc/(?P<team_pc>\d+)$', views.change_team_pc, name='panel_change_team_pc')
]

apps/billing/urls.py
from django.conf.urls import url
from apps.billing import views

app_name = "billing"
urlpatterns = [
    url("^pay/(?P<participation_id>[0-9]+)/$", views.payment, name='request_payment'),
    url("^payments/(?P<participation_id>[0-9]+)/$", views.payments_list, name='payments_list'),
    url("^complete/(?P<participation_id>[0-9]+)$", views.complete_payment, name='complete_payment'),
]

apps/accounts/views/authentication.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import generic
from django.views.generic import FormView, RedirectView
from apps.accounts.forms.forms import SignUpForm
from apps.accounts.tokens import account_activation_token


class SignupView(generic.CreateView):
    form_class = SignUpForm
    success_url = '/accounts/email_sent'
    template_name = 'accounts/profile/signup.html'

    def get_form_class(self):
        form = super().get_form_class()
        form.request = self.request
        return form


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect(to='/accounts/email_confirm')
    else:
        return redirect(to='/accounts/email_invalid')


def email_confirm(request):
    return render(request=request, template_name='email/email_confirm.html')


def email_invalid(request):
    return render(request=request, template_name='email/email_invalid.html')


def email_sent(request):
    return render(request=request, template_name='email/email_sent.html')


class LoginView(FormView):
    success_url = '/accounts/panel'
    form_class = AuthenticationForm
    template_name = 'accounts/profile/login.html'

    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

apps/accounts/views/panel.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from apps.accounts.forms.panel import SubmissionForm, ChallengeATeamForm
from apps.billing.decorators import payment_required
from apps.game.models import TeamSubmission, Match, TeamParticipatesChallenge, Competition
from django.core.paginator import Paginator
from django.db.models import Q

from apps.game.models.challenge import Challenge, UserAcceptsTeamInChallenge


@login_required
def get_team_pc(request):
    if request.user.profile.panel_active_teampc:
        return request.user.profile.panel_active_teampc
    try:
        pc = TeamParticipatesChallenge.objects.filter(team__participants__user=request.user).order_by('-id').first()
        request.user.profile.panel_active_teampc = pc
        request.user.profile.save()
        return pc
    except TeamParticipatesChallenge.DoesNotExist:
        return None


@login_required
def get_shared_context(request):
    context = {
        'challenges': Challenge.objects.all(),
        'invitations': [],
        'accepted_participations': []
    }

    all_participations = TeamParticipatesChallenge.objects.filter(
        team__participants__user=request.user
    )
    for challenge_participation in all_participations:
        if UserAcceptsTeamInChallenge.objects.filter(team=challenge_participation, user=request.user).exists():
            context['accepted_participations'].append(challenge_participation.team)

    context['user_pcs'] = []
    for tpc in TeamParticipatesChallenge.objects.filter(team__in=context['accepted_participations']):
        context['user_pcs'].append(tpc)

    context['menu_items'] = [
        {'name': 'team_management', 'link': reverse('accounts:panel_team_management'), 'text': _('Team Status')},
        {'name': 'submissions', 'link': reverse('accounts:panel_submissions'), 'text': _('Submissions')},
        {'name': 'battle_history', 'link': reverse('accounts:panel_battle_history'), 'text': _('Battle history')},
    ]

    if request.user.profile:
        if request.user.profile.panel_active_teampc:
            if request.user.profile.panel_active_teampc.should_pay and not request.user.profile.panel_active_teampc.has_paid:
                context['payment'] = request.user.profile.panel_active_teampc
            if request.user.profile.panel_active_teampc.challenge.competitions.filter(
                    type='friendly'
            ).exists():
                context['menu_items'].append(
                    {
                        'name': 'friendly_scoreboard',
                        'link': reverse('game:scoreboard', args=[
                            request.user.profile.panel_active_teampc.challenge.competitions.get(
                                type='friendly'
                            ).id
                        ]),
                        'text': _('Friendly Scoreboard')
                    }
                )

            if request.user.profile.panel_active_teampc.challenge.competitions.filter(
                    type='league'
            ).exists():
                context['menu_items'].append(
                    {
                        'name': 'friendly_scoreboard',
                        'link': reverse('game:league_scoreboard', args=[
                            request.user.profile.panel_active_teampc.challenge.id
                        ]),
                        'text': _('League')
                    }
                )

    return context


@login_required
def change_team_pc(request, team_pc):
    try:
        new_pc = TeamParticipatesChallenge.objects.get(team__participants__user=request.user, id=team_pc)
        request.user.profile.panel_active_teampc = new_pc
        request.user.profile.save()
    except TeamParticipatesChallenge.DoesNotExist:
        raise Http404
    return redirect('accounts:panel_team_management')


@payment_required
@login_required
def submissions(request):
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)

    for item in context['menu_items']:
        if item['name'] == 'submissions':
            item['active'] = True

    page = request.GET.get('page', 1)
    context.update({
        'page': page,
        'participation': team_pc,
        'participation_id': team_pc.id,
    })

    if request.method == 'POST':
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid() and form.cleaned_data['team'] == team_pc:
            form.save()
            return redirect('accounts:panel_submissions')
    else:
        form = SubmissionForm()

    context['submissions'] = Paginator(
        TeamSubmission.objects.filter(team_id=team_pc.id).order_by('-id'),
        5
    ).page(page)

    if team_pc is not None:
        form.initial['team'] = team_pc
        form.fields['team'].empty_label = None
        form.fields['file'].widget.attrs['accept'] = '.zip'

    context['form'] = form
    context['team_pc'] = team_pc
    return render(request, 'accounts/panel/submissions.html', context)


def redirect_to_somewhere_better(request):
    if Challenge.objects.filter(is_submission_open=True).exists():
        return HttpResponseRedirect(
            reverse(
                'accounts:create_team',
                args=[Challenge.objects.get(is_submission_open=True).id]
            )
        )
    else:
        return HttpResponseRedirect(reverse(
            'intro:index'
        ))


@login_required
def team_management(request, participation_id=None):
    if participation_id is not None:
        return change_team_pc(request, participation_id)
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)
    for item in context['menu_items']:
        if item['name'] == 'team_management':
            item['active'] = True
    context.update({
        'participation': team_pc,
        'participation_id': team_pc.id,
        'participation_members': [
            (
                user_part.user,
                not UserAcceptsTeamInChallenge.objects.filter(
                    user=user_part.user,
                    team=team_pc
                ).exists()
            )
            for user_part in team_pc.team.participants.all()] if team_pc else [],
        'challenges': Challenge.objects.all(),
        'invitations': [],
        'accepted_participations': []
    })

    all_participations = TeamParticipatesChallenge.objects.filter(
        team__participants__user=request.user
    )
    if all_participations.count() > 0 and team_pc is None:
        return redirect('accounts:panel', all_participations.first().id)
    for challenge_participation in all_participations:
        if not UserAcceptsTeamInChallenge.objects.filter(team=challenge_participation, user=request.user).exists():
            context['invitations'].append(challenge_participation)
        else:
            context['accepted_participations'].append(challenge_participation.team)
    return render(request, 'accounts/panel/team_management.html', context)


@payment_required
@login_required
def battle_history(request):
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)
    for item in context['menu_items']:
        if item['name'] == 'battle_history':
            item['active'] = True

    battles_page = request.GET.get('battles_page', 1)

    participation = team_pc
    if participation:
        participation_id = team_pc.id
        context.update({
            'participation': participation,
            'participation_id': participation_id,
        })

    if participation is not None and participation.challenge.competitions.filter(type='friendly').exists():
        context['form_challenge'] = ChallengeATeamForm(user=request.user, participation=participation)
        context['friendly_competition'] = participation.challenge.competitions.get(type='friendly')
        if participation is not None:
            context['challenge_teams'] = [team_part.team for team_part in
                                          TeamParticipatesChallenge.objects.filter(challenge=participation.challenge)]
            context.update({
                'battles_page': battles_page,
                'battle_history': Paginator(
                    Match.objects.filter(
                        Q(part1__object_id=participation_id) |
                        Q(part2__object_id=participation_id)).order_by('-id').filter(
                        competition__type='friendly'
                    ),
                    5).page(battles_page)
            })
    return render(request, 'accounts/panel/battle_history.html', context)

apps/accounts/views/profile.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from apps.accounts.forms.forms import UpdateProfileForm
from apps.accounts.models import Profile


class UpdateProfileView(LoginRequiredMixin, generic.UpdateView):
    form_class = UpdateProfileForm
    success_url = '/accounts/panel'
    template_name = 'accounts/profile/update_profile.html'
    model = Profile

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.id)

apps/accounts/views/team_required_and_finalized.py
def team_required_and_finalized(fn):
    pass
    def func(fn, *args, **kwargs):

        return func(fn, )

apps/accounts/templates/accounts/panel/battle_history.html
{% extends 'accounts/panel/panel.html' %}
{% load static i18n ai_filters tz %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block panel_content %}
    <h2 style="margin-top: 20px;">{% trans 'Battle history' %}</h2>
    {% if battle_history|length %}
        <table class="ui center aligned table table-bordered">
            <thead>
            <tr>
                <th>{% trans 'Time' %}</th>
                <th>{% trans 'Team' %}</th>
                <th>{% trans 'Score' %}</th>
                <th>{% trans 'Oponent Score' %}</th>
                <th>{% trans 'View' %}</th>
                <th>{% trans 'Log' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for match in battle_history %}
                <tr>
                    {% if LANGUAGE_BIDI %}
                    <td>{{ match.time.date|jalali }} - {{ match.time|time }}</td>
                    {% else %}
                    <td>{{ match.time.date }} - {{ match.time|time }}</td>
                    {% endif %}
                    {% if match.part1.depend == participation %}
                        <td>{{ match.part2.depend.team.name }}</td>
                        <td>{% if match.single_matches.first.log %}{{ match.score1 }}{% endif %}</td>
                        <td>{% if match.single_matches.first.log %}{{ match.score2 }}{% endif %}</td>
                        <td>
                            {% if match.single_matches.first.log %}
                                <a class="ui label"
                                   href="{% url 'game:game viewer' %}?log_url={{ match.single_matches.first.log.name }}&first_team={{ match.part1.depend.team.name|urlencode }}&second_team={{ match.part2.depend.team.name|urlencode }}">{% trans 'View' %}</a>
                            {% endif %}
                        </td>
                    {% elif match.part2.depend == participation %}
                        <td>{{ match.part1.depend.team.name }}</td>
                        <td>{% if match.single_matches.first.log %}{{ match.score2 }}{% endif %}</td>
                        <td>{% if match.single_matches.first.log %}{{ match.score1 }}{% endif %}</td>
                        <td>
                            {% if match.single_matches.first.log %}
                                <a class="ui label"
                                   href="{% url 'game:game viewer' %}?log_url={{ match.single_matches.first.log.name }}&first_team={{ match.part1.depend.team.name|urlencode }}&second_team={{ match.part2.depend.team.name|urlencode }}">{% trans 'View' %}</a>
                            {% endif %}
                        </td>
                    {% endif %}
                    <td>
                        {% if match.single_matches.first.log %}
                            <a class="ui green label" href="{{ match.single_matches.first.log.url }}">
                                {% trans 'Download' %}
                            </a>
                        {% else %}
                            <span class="ui blue label">{{ match.status }}</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            {% if battle_history.has_other_pages %}
                <tfoot>
                <tr>
                    <th colspan="6">
                        <div class="ui right floated pagination menu">
                            {% include 'accounts/panel/battle_history_paginator.html' %}
                        </div>
                    </th>
                </tr>
                </tfoot>
            {% endif %}
        </table>
    {% endif %}
    <form class="ui form" action="{% url 'accounts:challenge_a_team' participation_id %}" method="post"
          style="width: 100% !important;">
        {% csrf_token %}
        <div class="two fields">
            <div class="field">
                {{ form_challenge.battle_team.errors }}
                <label for="{{ form_challenge.battle_team.id_for_label }}">{% trans 'Versus:' %}
                </label>
                <select id="{{ form_challenge.battle_team.id_for_label }}" name="{{ form_challenge.battle_team.name }}"
                        class="ui search dropdown">
                    {% for choice in form_challenge.battle_team.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="field">
                {{ form_challenge.battle_team_maps.errors }}
                <label for="{{ form_challenge.battle_team_maps.id_for_label }}">{% trans 'Map:' %}
                </label>
                <select id="{{ form_challenge.battle_team_maps.id_for_label }}"
                        name="{{ form_challenge.battle_team_maps.name }}" class="ui dropdown">
                    {% for choice in form_challenge.battle_team_maps.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <input type="submit" class="ui green button" value="{% trans 'Submit' %}">
    </form>

{% endblock %}

apps/accounts/templates/accounts/panel/battle_history_paginator.html
{% if battle_history.has_previous %}
    <a class="icon item"
       href="?page={{ page }}&battles_page={{ battle_history.previous_page_number }}">
        <i class="{% if LANGUAGE_BIDI %}right{% else %}left{% endif %} chevron icon"></i>
    </a>
{% else %}
    <a class="disabled icon item">
        <i class="{% if LANGUAGE_BIDI %}right{% else %}left{% endif %} chevron icon"></i>
    </a>
{% endif %}


{% if battle_history.paginator.num_pages <= 5 %}
    {% for i in battle_history.paginator.page_range %}
        {% if battle_history.number == i %}
            <a class="active item"><span>{{ i }}</span></a>
        {% else %}
            <a class="item"
               href="?page={{ page }}&battles_page={{ i }}"><span>{{ i }}</span></a>
        {% endif %}
    {% endfor %}
{% else %}
    {% for i in '123'|make_list %}
        {% if battle_history.number == forloop.counter %}
            <a class="active item"><span>{{ i }}</span></a>
        {% else %}
            <a class="item" href="?page={{ page }}&battles_page={{ i }}"><span>{{ i }}</span></a>
        {% endif %}
    {% endfor %}
    <a class="disabled item">...</a>
    {% with battle_history.paginator.num_pages as i %}
        <a class="item" href="?page={{ page }}&battles_page={{ i }}"><span>{{ i }}</span></a>
    {% endwith %}
{% endif %}


{% if battle_history.has_next %}
    <a class="icon item"
       href="?page={{ page }}&battles_page={{ battle_history.next_page_number }}">
        <i class="{% if LANGUAGE_BIDI %}left{% else %}right{% endif %} chevron icon"></i>
    </a>
{% else %}
    <a class="disabled icon item">
        <i class="{% if LANGUAGE_BIDI %}left{% else %}right{% endif %} chevron icon"></i>
    </a>
{% endif %}

apps/accounts/templates/accounts/panel/challenge_feild.html
{% load i18n %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}


<div id="last_teampc" class="ui fluid selection dropdown">
    <div class="text">{{ participation }}</div>
    <i class="dropdown icon"></i>
    <div class="menu">
        {% for choice in user_pcs %}
            <a class="item{% if choice == participation %} active{% endif %}" href="{% url 'accounts:panel_change_team_pc' choice.id %}">{{ choice }}</a>
        {% endfor %}
    </div>
</div>

apps/accounts/templates/accounts/panel/friendly_result.html
{% extends 'base/base.html' %}
{% load i18n %}

{% block container %}
    {% if form.errors|length %}
        <div class="ui error message">
            <strong>{% trans 'Error scheduling match.' %}</strong>
            {% for error in form.non_field_errors %}
                <p>
                    <br>
                    <strong>{{ error|escape }}</strong>
                </p>
            {% endfor %}
        </div>
    {% else %}
        <div class="ui success message">
            {% trans 'Successfully scheduled friendly match.' %}
        </div>
    {% endif %}
    <a class="ui primary button" href="{% url 'accounts:panel' %}">{% trans 'Panel' %}</a>
{% endblock %}

apps/accounts/templates/accounts/panel/messages.html
{% load i18n %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% for invitation in invitations %}
    <div class="ui info message">
        <i onclick="window.location.href='{% url "accounts:reject_participation" invitation.id %}';"
           class="close icon"></i>
        <div class="header">
            <p>{% trans 'You are invited to the team ' %}"{{ invitation.team }}"{% trans ' on the challenge ' %}"{{ invitation.challenge }}"{% trans ', do you accept?' %}</p>
            <p>{% trans 'Members are:' %}</p>
        </div>
        <ul class="list">
            {% for participant in invitation.team.participants.all %}
                <li>{{ participant.user.username }}: {{ participant.user.first_name }} {{ participant.user.last_name }}</li>
            {% endfor %}
        </ul>
        <br>
        <div class="ui buttons">
            <a href="{% url 'accounts:accept_participation' invitation.id %}"
               class="ui right aligned green button">{% trans 'Accept' %}</a>
            <a href="{% url 'accounts:reject_participation' invitation.id %}"
               class="ui right aligned red button">{% trans 'Reject' %}</a>
        </div>
    </div>
{% endfor %}

{% if payment %}
    <div class="ui info message">
        <div class="header">
            <p>{% trans 'You have to complete the team and pay to continue to this challenge.' %}</p>
        </div>
        <br>
        <a href="{% url 'billing:request_payment' payment.id %}"
           class="ui right aligned green button">
            {% if payment.is_complete %}
                {% trans 'Pay' %}
            {% else %}
                {% trans 'Complete team' %}
            {% endif %}
        </a>
    </div>
{% endif %}

apps/accounts/templates/accounts/panel/panel.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block container %}
    {% include 'accounts/panel/messages.html' %}


    <div class="ui stackable grid">
        <div class="four wide column">
            {% include 'accounts/panel/challenge_feild.html' %}
            <div class="ui secondary vertical pointing fluid menu mobile-hidden">
                {% for item in menu_items %}
                    <a class="item{% if item.active %} active{% endif %}" href="{{ item.link }}">
                        {{ item.text }}
                    </a>
                {% endfor %}
            </div>
            <div class="ui secondary pointing fluid menu mobile-only">
                {% for item in menu_items %}
                    <a class="item{% if item.active %} active{% endif %}" href="{{ item.link }}">
                        {{ item.text }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="twelve wide column">
            {% block panel_content %}
                NOTHING HERE... YET!
            {% endblock %}
        </div>
    </div>
    <script src="{% static 'accounts/js/api.js' %}"></script>
{% endblock %}

apps/accounts/templates/accounts/panel/team_management.html
{% extends 'accounts/panel/panel.html' %}
{% load static i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block panel_content %}
    <h2>{% trans 'Team Status' %}</h2>
    <div>
    {% if accepted_participations|length > 0 %}
        <table class="ui center aligned table">
            <thead>
            <tr>
                <th>{% trans 'Username' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for user, removable in participation_members %}
                <tr>
                    <td>{{ user }}</td>
                    <td>
                        {% if removable %}

                            <a href="{% url 'accounts:cancel_participation_request' participation.id user.id %}"
                               class="ui right aligned red button tiny">
                                <i class="remove icon"></i>
                                {% trans 'Remove' %}
                            </a>
                        {% else %}
                            <span class="ui right aligned green button tiny">
                                    <i class="checkmark icon"></i>
                                    {% trans 'Accepted' %}
                                </span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            {% if participation_members|length < participation.challenge.team_size %}
                <tr>
                    <td>
                        <a href="{% url 'accounts:add_participation' participation.id %}"
                           class="ui right aligned green button tiny">
                            <i class="add icon"></i>
                            {% trans 'Add a member' %}
                        </a>
                    </td>
                    <td></td>
                </tr>
            {% endif %}
            </tbody>
            <tfoot>
            <tr>
                <th colspan="2">
                    {% if participation %}
                        {% if participation.all_members_accepted %}
                            {% trans "All users have accepted the challenge." %}
                        {% else %}
                            {% trans "All users haven't accepted the challenge yet!" %}
                        {% endif %}
                    {% endif %}
                </th>
            </tr>
            </tfoot>
        </table>

    {% else %}
        {% trans 'You have not participated in this challenge yet.' %}
    {% endif %}
    </div>
{% endblock %}