aic_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from apps.intro import urls as intro_urls
from apps.accounts import urls as account_urls
from apps.game import urls as game_urls
from zinnia import urls as zinnia_urls
from apps.game import urls as game_urls
from apps.billing import urls as billing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(intro_urls)),

    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^accounts/', include(account_urls)),
    url(r'^blog/', include(zinnia_urls)),
    url(r'^game/', include(game_urls)),
    url(r'^articles/comments/', include('django_comments.urls')),
    url(r'^tinymce/filebrowser/', include('zinnia_tinymce.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^billing/', include(billing_urls))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts import views

app_name = "accounts"
urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^update_profile/$', views.UpdateProfileView.as_view(), name='update_profile'),
    url(r'^create_team/(?P<challenge_id>[0-9]+)$', views.create_team, name='create_team'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create_team/success_create_team$', views.success_create_team, name='success_create_team'),
    url(r'^panel/(?P<participation_id>[0-9]+)?$', views.team_management, name='panel'),
    url(r'^panel/accept_participation/(?P<participation_id>[0-9]+)$', views.accept_participation,
        name='accept_participation'),
    url(r'^panel/reject_participation/(?P<participation_id>[0-9]+)$', views.reject_participation,
        name='reject_participation'),
    url(r'^panel/cancel_participation/(?P<participation_id>[0-9]+)/(?P<user_id>[0-9]+)$',
        views.cancel_participation_request, name='cancel_participation_request'),
    url(r'^panel/add_participation/(?P<participation_id>[0-9]+)$', views.add_participation,
        name='add_participation'),
    url(r'^panel/set_final_submission/(?P<submission_id>[0-9]+)', views.set_final_submission,
        name='set final submission'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^email_sent$', views.email_sent, name='email_sent'),
    url(r'^email_confirm$', views.email_confirm, name='email_confirm'),
    url(r'^email_invalid$', views.email_invalid, name='email_invalid'),
    url(r'^challenge_a_team/(?P<participation_id>\d+)$', views.challenge_a_team, name='challenge_a_team'),

    url(r'^panel/submissions', views.submissions, name='panel_submissions'),
    url(r'^panel/team$', views.team_management, name='panel_team_management'),
    url(r'^panel/bhistory', views.battle_history, name='panel_battle_history'),
    url(r'^panel/teampc/(?P<team_pc>\d+)$', views.change_team_pc, name='panel_change_team_pc')
]

templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %}{% endblock title %}

{% block body-class %}author-list{% endblock body-class %}

{% block container %}
<h1>{% trans "Author list" %}</h1>

<ul>
  {% for object in object_list %}
  <li class="vcard">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock container %}

templates/zinnia/base.html
{% extends "base/base.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", " }}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}"/>
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia:entry_archive_index' %}"/>
    <link rel="author" type="text/plain" href="{% url 'zinnia:humans' %}"/>
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia:rsd' %}"/>
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia:wlwmanifest' %}"/>
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog"
          href="{% url 'zinnia:opensearch' %}"/>
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last entries" %}"
          href="{% url 'zinnia:entry_feed' %}"/>
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last discussions" %}"
          href="{% url 'zinnia:discussion_feed' %}"/>
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block breadcrumbs %}
    {% trans "Blog" as root_name %}
    {% zinnia_breadcrumbs root_name %}
{% endblock breadcrumbs %}

{% block sidebar %}
    <div class="ui right sidebar inverted vertical menu">
    {% for title, link in ai.sidebar.items %}
            {% if not link.dropdown %}
                <a href="{{ link.address }}" class="{% if link.active %}active {% endif %}item">{{ title }}</a>
            {% else %}
                <div class="item">
                    <div class="title">
                        <span class="text">{{ title }}</span>
                    </div>
                    <div class="content menu">
                        {% for dtitle, dlink in link.dropdown.items %}
                            <a href="{{ dlink }}" class="item">{{ dtitle }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
    {% endfor %}
<div id="widget-tags" class="item">
            <div class="item">
                <div class="header">
                    {% trans "Tags" %}
                </div>
            </div>
            <div class="content menu">
                {% get_tag_cloud %}
            </div>
        </div>
        <div id="widget-recents" class="item">
            <div class="item">
                <div class="title">{% trans "Recent entries" %}</div>
            </div>
            <div class="content menu">
                {% get_recent_entries %}
            </div>
        </div>
        <div id="widget-comments" class="item">
            <div class="item">
                <div class="header">{% trans "Recent comments" %}</div>
            </div>
            <div class="content menu">
                {% get_recent_comments %}
            </div>
        </div>

</div>
{% endblock sidebar %}

templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %}{% endblock title %}

{% block body-class %}category-list{% endblock body-class %}

{% block container %}
<h1>{% trans "Category list" %}</h1>

<ul>
  {% for object in object_list %}
  <li>
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with category=object %}Show all entries in {{ category }}{% endblocktrans %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    {% if object.description %}<p>{{ object.description|striptags|safe }}</p>{% endif %}
  </li>
  {% empty %}
  <li>
    {% trans "No categories yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock container %}

templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Last entries" %}{% endblock meta-description %}

{% block title %}{% trans "Last entries" %}{% endblock title %}

{% block body-class %}{{ block.super }} archive index {% now "\y\e\a\r-Y \m\o\n\t\h-m \w\e\ek-W \d\a\y-d" %}{% endblock body-class %}

{% block slider %}
{% get_featured_entries template="zinnia/tags/entries_slider.html" %}
{% endblock slider %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Yearly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_year' date|date:"Y" %}" rel="archives">{{ date|date:"Y" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content-related %}

templates/zinnia/entry_archive_day.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date day year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}
{% if next_day %}
<h3>{% trans "Next day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' next_day|date:"Y" next_day|date:"m" next_day|date:"d" %}" rel="archives">{{ next_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_week' day|date:"Y" day|week_number %}" rel="archives">
      {% blocktrans with year=day|date:"Y" week_number=day|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
    </a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% if next_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' next_month|date:"Y" next_month|date:"m" %}" rel="archives">{{ next_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
</ul>
{% endblock content-related %}

templates/zinnia/entry_archive_today.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date today year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Today archives" %}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

templates/zinnia/entry_archive_week.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock meta-description %}

{% block title %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock title %}

{% block body-class %}{{ block.super }} archive date week year-{{ week|date:"Y" }} month-{{ week|date:"m" }} week-{{ week|week_number }}{% endblock body-class %}

{% block content-title %}
<h1>{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}</h1>
<h2>{{ week|date:"DATE_FORMAT" }} - {{ week_end_day|date:"DATE_FORMAT" }}</h2>
{% endblock content-title %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Daily archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_day' date|date:"Y" date|date:"m" date|date:"d" %}" rel="archives">{{ date|date:"DATE_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% if previous_week %}
<h3>{% trans "Previous week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' previous_week|date:"Y" previous_week|week_number %}" rel="archives">
    {% blocktrans with year=previous_week|date:"Y" week_number=previous_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
{% if next_week %}
<h3>{% trans "Next week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' next_week|date:"Y" next_week|week_number %}" rel="archives">
    {% blocktrans with year=next_week|date:"Y" week_number=next_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' week|date:"Y" %}" rel="archives">{{ week|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_month' week|date:"Y" week|date:"m" %}" rel="archives">{{ week|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

templates/zinnia/entry_archive_year.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Archives" %} {{ year|date:"Y" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ year|date:"Y" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date year year-{{ year|date:"Y" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ year|date:"Y" }}</h1>
{% endblock content-title %}

{% block content-related %}
<h2>{% trans "Monthly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' date|date:"Y" date|date:"m" %}" rel="archives">{{ date|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>

{% if previous_year %}
<h3>{% trans "Previous year" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_year' previous_year|date:"Y" %}" rel="archives">{{ previous_year|date:"Y" }}</a>
</p>
{% endif %}
{% if next_year %}
<h3>{% trans "Next year" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_year' next_year|date:"Y" %}" rel="archives">{{ next_year|date:"Y" }}</a>
</p>
{% endif %}
{% endblock content-related %}

templates/zinnia/entry_detail_base.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load zinnia %}
{% load threadedcomments_tags %}
{% load static %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% load ai_filters %}

{% block title %}{{ object.title }}{% endblock title %}

{% block meta-description %}{{ object.excerpt|safe }}{% endblock meta-description %}

{% block meta-keywords %}{% if object.tags %}{{ object.tags }}{% else %}{{ block.super }}
{% endif %}{% endblock meta-keywords %}

{% block link %}
    {{ block.super }}
    {% with previous_entry=object.previous_entry %}{% if previous_entry %}
        <link rel="prev" title="{{ previous_entry.title }}" href="{{ previous_entry.get_absolute_url }}"/>
    {% endif %}{% endwith %}
    {% with next_entry=object.next_entry %}{% if next_entry %}
        <link rel="next" title="{{ next_entry.title }}" href="{{ next_entry.get_absolute_url }}"/>
    {% endif %}{% endwith %}
    <link rel="shortlink" href="{{ object.short_url }}"/>
    <link rel="canonical" href="{{ object.get_absolute_url }}"/>
    {% with year=object.publication_date|date:"Y" month=object.publication_date|date:"m" day=object.publication_date|date:"d" %}
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=object.title %}RSS feed of discussions on {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:entry_discussion_feed' year month day object.slug %}"/>
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=object.title %}RSS feed of comments on {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:entry_comment_feed' year month day object.slug %}"/>
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=object.title %}RSS feed of pingbacks on {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:entry_pingback_feed' year month day object.slug %}"/>
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=object.title %}RSS feed of trackbacks on {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:entry_trackback_feed' year month day object.slug %}"/>
    {% endwith %}
{% endblock link %}

{% block body-class %}entry entry-
    {{ object.pk }}{% if object.featured %} featured{% endif %} year-{{ object.publication_date|date:"Y" }} month-
    {{ object.publication_date|date:"m" }} week-{{ object.publication_date|date:"W" }} day-
    {{ object.publication_date|date:"d" }}{% endblock body-class %}

{% block container %}

    {% block entry-content %}
        {% include object.content_template with object_content=object.html_content %}
    {% endblock entry-content %}



    {% block entry-comments %}
        <section id="comments">
            {% if object.comment_count %}
                {% with comment_list=object.comments %}
                    <div class="ui comments" id="comments-container">
                        {% block comments-loop %}

                            <!-- ### Sample rendering of comments ###-->
                            <!-- reference: -->
                            <!-- https://pypi.python.org/pypi/django-threadedcomments -->

                            <h3 class="ui dividing header">{% trans 'Comments and Q&A' %}</h3>

                            {% get_comment_list for object as object_comments %}
                            {% for object_comment in object_comments %}
                                {% get_comment_list for object_comment as comment_comments %}
                                <div class="comment" id="c{{ object_comment.id }}">
                                    <div class="avatar">
                                        {% block comment-image-noanswer %}
                                            {% if comment.user.is_staff %}
                                                <img class="large image" src="{% static 'images/admin.png' %}">
                                            {% else %}
                                                <img src="{% static 'images/user.jpeg' %}">
{#                                            <img src="{% get_gravatar comment.email 60 "G" %}"#}
{#                                                 class="gravatar photo" alt="{{ comment.name }}"/>#}
                                            {% endif %}
                                        {% endblock comment-image-noanswer %}
                                    </div>
                                    <div class="content">
                                        <div class="metadata">
                                            <span class="date">
                                                {% block comment-info-noanswer %}
                                                    <p class="comment-info">
                                                    {% blocktrans with comment_title=object_comment.title|default:"#" comment_url=object_comment.url|default:"#" comment_name=object_comment.name comment_human_date=object_comment.submit_date|date:"SHORT_DATETIME_FORMAT"|jalali comment_technical_date=object_comment.submit_date|date:"c" comment_pk=object_comment.pk comment_author_slug=object_comment.user_name|slugify trimmed %}
                                                        <a href="#comment-{{ comment_pk }}-by-{{ comment_author_slug }}"
                                                           id="c{{ comment_pk }}" class="anchor-link ui header"
                                                           title="Direct link to this comment" class="large"> {{ comment_title }} </a>

                                                        <a href="{{ comment_url }}" rel="external nofollow"
                                                           class="fn url header">{{ comment_name }}</a>
                                                        on
                                                        <time class="comment-published" datetime="{{ comment_technical_date }}">
                                                            {{ comment_human_date }}
                                                        </time>
                                                    {% endblocktrans %}
                                                </p>
                                                {% endblock comment-info-noanswer %}
                                            </span>
                                        </div>
                                        <div class="text">
                                            {% block comment-content-noanswer %}
                                                {{ object_comment.comment|linebreaks }}
                                            {% endblock comment-content-noanswer %}
                                            {#            end comment #}
                                        </div>
                                    </div>
                                    <div class="comments">
                                        {% for comment in comment_comments %}
                                            <div class="comment" id="c{{ comment.id }}">
                                                <div class="avatar">
                                                {% block comment-image %}
                                                    {% if comment.user.is_staff %}
                                                        <img class="large image" src="{% static 'images/admin.png' %}">
                                                    {% else %}
                                                        <img src="{% static 'images/user.jpeg' %}">
        {#                                            <img src="{% get_gravatar comment.email 60 "G" %}"#}
        {#                                                 class="gravatar photo" alt="{{ comment.name }}"/>#}
                                                    {% endif %}
                                                {% endblock comment-image %}
                                                </div>
                                                <div class="content">
                                                    <div class="metadata">
                                                        <span class="date">
                                                            {% block comment-info %}
                                                                <p class="comment-info">
                                                                {% blocktrans with comment_title=comment.title|default:"" comment_url=comment.url|default:"#" comment_name=comment.name comment_human_date=comment.submit_date|date:"SHORT_DATETIME_FORMAT"|jalali comment_technical_date=comment.submit_date|date:"c" comment_pk=comment.pk comment_author_slug=comment.user_name|slugify trimmed %}
                                                                    <a href="#comment-{{ comment_pk }}-by-{{ comment_author_slug }}"
                                                                       id="c{{ comment_pk }}" class="anchor-link ui header"
                                                                       title="Direct link to this comment">{{ comment_title }}</a>
                                                                    <a href="{{ comment_url }}" rel="external nofollow"
                                                                       class="fn url large">{{ comment_name }}</a>
                                                                    on
                                                                    <time class="comment-published" datetime="{{ comment_technical_date }}">
                                                                        {{ comment_human_date }}
                                                                    </time>
                                                                {% endblocktrans %}
                                                            </p>
                                                            {% endblock comment-info %}
                                                        </span>
                                                    </div>
                                                    <div class="text">
                                                        {% block comment-content %}
                                                            {{ comment.comment|linebreaks }}
                                                        {% endblock comment-content %}
                                                        {#            end comment #}
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                        {% if request.user.is_staff %}
                                            {% render_comment_form for object_comment with object_comment.id %}
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}

                        {% endblock comments-loop %}
                    </div>
                {% endwith %}
                {% if not object.comments_are_open %}
                    <p>{% trans "Comments are closed." %}</p>
                {% endif %}
            {% else %}
                {% if object.comments_are_open %}
                    <p>{% trans "No comments yet." %}</p>
                {% else %}
                    <p>{% trans "Comments are closed." %}</p>
                {% endif %}
            {% endif %}
        </section>
    {% endblock entry-comments %}

    {% block entry-comments-form %}
        {% if request.user.is_authenticated %} {# comment it if Unauthenticated users can register #}
            {% if object.comments_are_open %}
                {% render_comment_form for object %}
            {% endif %}
        {% else %}
            <a href="{% url 'accounts:login' %}" class="ui primary button">{%  trans 'Login To Comment' %}</a>
        {% endif %}
    {% endblock entry-comments-form %}

{% endblock container %}

{% block admin-tools %}
    {% if perms.zinnia.change_entry %}
        <li>
            <a href="{% url 'admin:zinnia_entry_change' object.pk %}" title="{% trans "Edit the entry" %}">
                {% trans "Edit the entry" %}
            </a>
        </li>
    {% endif %}
{% endblock admin-tools %}