aic_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from apps.intro import urls as intro_urls
from apps.accounts import urls as account_urls
from apps.game import urls as game_urls
from zinnia import urls as zinnia_urls
from apps.game import urls as game_urls
from apps.billing import urls as billing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(intro_urls)),

    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^accounts/', include(account_urls)),
    url(r'^blog/', include(zinnia_urls)),
    url(r'^game/', include(game_urls)),
    url(r'^articles/comments/', include('django_comments.urls')),
    url(r'^tinymce/filebrowser/', include('zinnia_tinymce.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^billing/', include(billing_urls))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts import views

app_name = "accounts"
urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^update_profile/$', views.UpdateProfileView.as_view(), name='update_profile'),
    url(r'^create_team/(?P<challenge_id>[0-9]+)$', views.create_team, name='create_team'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create_team/success_create_team$', views.success_create_team, name='success_create_team'),
    url(r'^panel/(?P<participation_id>[0-9]+)?$', views.team_management, name='panel'),
    url(r'^panel/accept_participation/(?P<participation_id>[0-9]+)$', views.accept_participation,
        name='accept_participation'),
    url(r'^panel/reject_participation/(?P<participation_id>[0-9]+)$', views.reject_participation,
        name='reject_participation'),
    url(r'^panel/cancel_participation/(?P<participation_id>[0-9]+)/(?P<user_id>[0-9]+)$',
        views.cancel_participation_request, name='cancel_participation_request'),
    url(r'^panel/add_participation/(?P<participation_id>[0-9]+)$', views.add_participation,
        name='add_participation'),
    url(r'^panel/set_final_submission/(?P<submission_id>[0-9]+)', views.set_final_submission,
        name='set final submission'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^email_sent$', views.email_sent, name='email_sent'),
    url(r'^email_confirm$', views.email_confirm, name='email_confirm'),
    url(r'^email_invalid$', views.email_invalid, name='email_invalid'),
    url(r'^challenge_a_team/(?P<participation_id>\d+)$', views.challenge_a_team, name='challenge_a_team'),

    url(r'^panel/submissions', views.submissions, name='panel_submissions'),
    url(r'^panel/team$', views.team_management, name='panel_team_management'),
    url(r'^panel/bhistory', views.battle_history, name='panel_battle_history'),
    url(r'^panel/teampc/(?P<team_pc>\d+)$', views.change_team_pc, name='panel_change_team_pc')
]

templates/comments/zinnia/entry/form.html
{% load comments i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<form action="{% comment_form_target %}" method="post" id="comment-form">
    <div>{% csrf_token %}</div>
    {% if form.non_field_errors %}
        <div class="error">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <div>
        <input type="hidden" name="next" value="{% url 'zinnia:comment_success' %}"/>

        {% for field in form %}
            {% if field.is_hidden %}{{ field }}{% endif %}
        {% endfor %}


        <div class="ui form" style="margin-{% if LANGUAGE_BIDI %}right{% else %}left{% endif %}: 0px;" id="post-a-comment-form">
            <div class="field" id="comment-form-title">
            {% if user.email and form.title.name in "namemailurl" %}{% else %}
                <div{% if form.title.errors %} class="error"{% endif %}{% ifequal field.name "honeypot" %}
                                               style="display:none;"{% endifequal %}>
                    <label>{{ form.title.label_tag }}</label>
                    {% if form.title.errors %}{{ form.title.errors }}{% endif %}
                    {{ form.title }}
                </div>
            {% endif %}
            </div>
            <div class="field">
            {% if user.email and form.comment.name in "namemailurl" %}{% else %}
                <div{% if form.comment.errors %} class="error"{% endif %}{% ifequal form.comment.name "honeypot" %}
                                                 style="display:none;"{% endifequal %}>
                    <label>{{ form.comment.label_tag }}</label>
                    {% if form.comment.errors %}{{ form.comment.errors }}{% endif %}
                    {{ form.comment }}
                </div>
            {% endif %}
            </div>

        </div>

        {% if user.is_authenticated %}
            <p class="auth">
                {% trans "Comment as" %} <strong>{% firstof user.get_full_name user.get_username %}</strong> <a
                    href="{% url 'accounts:logout' %}">{% trans "Log out" %}</a>
            </p>
        {% else %}
            <p></p>
        {% endif %}
        <p class="submit">
            <input type="submit" name="submit" class="ui primary button" value="{% trans "Post" %}"/>
{#                        <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}"/>#}
        </p>
    </div>
</form>

templates/comments/zinnia/entry/posted.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for your comment" %}{% endblock title %}

{% block body-class %}comment-posted{% endblock body-class %}

{% block container %}
<h2>{% trans "Thanks for your comment" %}</h2>

<p>{% trans "Your comment needs to be approved before getting displayed." %}</p>

<ul>
  {% if comment %}
  <li>
    {% with entry=comment.content_object %}
    <a href="{{ entry.get_absolute_url }}"
       title="{{ entry.title }}">
      {% blocktrans with title=entry.title %}Back to {{ title }}{% endblocktrans %}
    </a>
    {% endwith %}
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_index' %}"
       title="{% trans "Return to entry list" %}">
      {% trans "Return to entry list" %}
    </a>
  </li>
</ul>
{% endblock container %}