aic_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from apps.intro import urls as intro_urls
from apps.accounts import urls as account_urls
from apps.game import urls as game_urls
from zinnia import urls as zinnia_urls
from apps.game import urls as game_urls
from apps.billing import urls as billing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(intro_urls)),

    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^accounts/', include(account_urls)),
    url(r'^blog/', include(zinnia_urls)),
    url(r'^game/', include(game_urls)),
    url(r'^articles/comments/', include('django_comments.urls')),
    url(r'^tinymce/filebrowser/', include('zinnia_tinymce.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^billing/', include(billing_urls))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts import views

app_name = "accounts"
urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^update_profile/$', views.UpdateProfileView.as_view(), name='update_profile'),
    url(r'^create_team/(?P<challenge_id>[0-9]+)$', views.create_team, name='create_team'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create_team/success_create_team$', views.success_create_team, name='success_create_team'),
    url(r'^panel/(?P<participation_id>[0-9]+)?$', views.team_management, name='panel'),
    url(r'^panel/accept_participation/(?P<participation_id>[0-9]+)$', views.accept_participation,
        name='accept_participation'),
    url(r'^panel/reject_participation/(?P<participation_id>[0-9]+)$', views.reject_participation,
        name='reject_participation'),
    url(r'^panel/cancel_participation/(?P<participation_id>[0-9]+)/(?P<user_id>[0-9]+)$',
        views.cancel_participation_request, name='cancel_participation_request'),
    url(r'^panel/add_participation/(?P<participation_id>[0-9]+)$', views.add_participation,
        name='add_participation'),
    url(r'^panel/set_final_submission/(?P<submission_id>[0-9]+)', views.set_final_submission,
        name='set final submission'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^email_sent$', views.email_sent, name='email_sent'),
    url(r'^email_confirm$', views.email_confirm, name='email_confirm'),
    url(r'^email_invalid$', views.email_invalid, name='email_invalid'),
    url(r'^challenge_a_team/(?P<participation_id>\d+)$', views.challenge_a_team, name='challenge_a_team'),

    url(r'^panel/submissions', views.submissions, name='panel_submissions'),
    url(r'^panel/team$', views.team_management, name='panel_team_management'),
    url(r'^panel/bhistory', views.battle_history, name='panel_battle_history'),
    url(r'^panel/teampc/(?P<team_pc>\d+)$', views.change_team_pc, name='panel_change_team_pc')
]

apps/accounts/views/authentication.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import generic
from django.views.generic import FormView, RedirectView
from apps.accounts.forms.forms import SignUpForm
from apps.accounts.tokens import account_activation_token


class SignupView(generic.CreateView):
    form_class = SignUpForm
    success_url = '/accounts/email_sent'
    template_name = 'accounts/profile/signup.html'

    def get_form_class(self):
        form = super().get_form_class()
        form.request = self.request
        return form


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect(to='/accounts/email_confirm')
    else:
        return redirect(to='/accounts/email_invalid')


def email_confirm(request):
    return render(request=request, template_name='email/email_confirm.html')


def email_invalid(request):
    return render(request=request, template_name='email/email_invalid.html')


def email_sent(request):
    return render(request=request, template_name='email/email_sent.html')


class LoginView(FormView):
    success_url = '/accounts/panel'
    form_class = AuthenticationForm
    template_name = 'accounts/profile/login.html'

    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

apps/accounts/views/panel.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from apps.accounts.forms.panel import SubmissionForm, ChallengeATeamForm
from apps.billing.decorators import payment_required
from apps.game.models import TeamSubmission, Match, TeamParticipatesChallenge, Competition
from django.core.paginator import Paginator
from django.db.models import Q

from apps.game.models.challenge import Challenge, UserAcceptsTeamInChallenge


@login_required
def get_team_pc(request):
    if request.user.profile.panel_active_teampc:
        return request.user.profile.panel_active_teampc
    try:
        pc = TeamParticipatesChallenge.objects.filter(team__participants__user=request.user).order_by('-id').first()
        request.user.profile.panel_active_teampc = pc
        request.user.profile.save()
        return pc
    except TeamParticipatesChallenge.DoesNotExist:
        return None


@login_required
def get_shared_context(request):
    context = {
        'challenges': Challenge.objects.all(),
        'invitations': [],
        'accepted_participations': []
    }

    all_participations = TeamParticipatesChallenge.objects.filter(
        team__participants__user=request.user
    )
    for challenge_participation in all_participations:
        if UserAcceptsTeamInChallenge.objects.filter(team=challenge_participation, user=request.user).exists():
            context['accepted_participations'].append(challenge_participation.team)

    context['user_pcs'] = []
    for tpc in TeamParticipatesChallenge.objects.filter(team__in=context['accepted_participations']):
        context['user_pcs'].append(tpc)

    context['menu_items'] = [
        {'name': 'team_management', 'link': reverse('accounts:panel_team_management'), 'text': _('Team Status')},
        {'name': 'submissions', 'link': reverse('accounts:panel_submissions'), 'text': _('Submissions')},
        {'name': 'battle_history', 'link': reverse('accounts:panel_battle_history'), 'text': _('Battle history')},
    ]

    if request.user.profile:
        if request.user.profile.panel_active_teampc:
            if request.user.profile.panel_active_teampc.should_pay and not request.user.profile.panel_active_teampc.has_paid:
                context['payment'] = request.user.profile.panel_active_teampc
            if request.user.profile.panel_active_teampc.challenge.competitions.filter(
                    type='friendly'
            ).exists():
                context['menu_items'].append(
                    {
                        'name': 'friendly_scoreboard',
                        'link': reverse('game:scoreboard', args=[
                            request.user.profile.panel_active_teampc.challenge.competitions.get(
                                type='friendly'
                            ).id
                        ]),
                        'text': _('Friendly Scoreboard')
                    }
                )

            if request.user.profile.panel_active_teampc.challenge.competitions.filter(
                    type='league'
            ).exists():
                context['menu_items'].append(
                    {
                        'name': 'friendly_scoreboard',
                        'link': reverse('game:league_scoreboard', args=[
                            request.user.profile.panel_active_teampc.challenge.id
                        ]),
                        'text': _('League')
                    }
                )

    return context


@login_required
def change_team_pc(request, team_pc):
    try:
        new_pc = TeamParticipatesChallenge.objects.get(team__participants__user=request.user, id=team_pc)
        request.user.profile.panel_active_teampc = new_pc
        request.user.profile.save()
    except TeamParticipatesChallenge.DoesNotExist:
        raise Http404
    return redirect('accounts:panel_team_management')


@payment_required
@login_required
def submissions(request):
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)

    for item in context['menu_items']:
        if item['name'] == 'submissions':
            item['active'] = True

    page = request.GET.get('page', 1)
    context.update({
        'page': page,
        'participation': team_pc,
        'participation_id': team_pc.id,
    })

    if request.method == 'POST':
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid() and form.cleaned_data['team'] == team_pc:
            form.save()
            return redirect('accounts:panel_submissions')
    else:
        form = SubmissionForm()

    context['submissions'] = Paginator(
        TeamSubmission.objects.filter(team_id=team_pc.id).order_by('-id'),
        5
    ).page(page)

    if team_pc is not None:
        form.initial['team'] = team_pc
        form.fields['team'].empty_label = None
        form.fields['file'].widget.attrs['accept'] = '.zip'

    context['form'] = form
    context['team_pc'] = team_pc
    return render(request, 'accounts/panel/submissions.html', context)


def redirect_to_somewhere_better(request):
    if Challenge.objects.filter(is_submission_open=True).exists():
        return HttpResponseRedirect(
            reverse(
                'accounts:create_team',
                args=[Challenge.objects.get(is_submission_open=True).id]
            )
        )
    else:
        return HttpResponseRedirect(reverse(
            'intro:index'
        ))


@login_required
def team_management(request, participation_id=None):
    if participation_id is not None:
        return change_team_pc(request, participation_id)
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)
    for item in context['menu_items']:
        if item['name'] == 'team_management':
            item['active'] = True
    context.update({
        'participation': team_pc,
        'participation_id': team_pc.id,
        'participation_members': [
            (
                user_part.user,
                not UserAcceptsTeamInChallenge.objects.filter(
                    user=user_part.user,
                    team=team_pc
                ).exists()
            )
            for user_part in team_pc.team.participants.all()] if team_pc else [],
        'challenges': Challenge.objects.all(),
        'invitations': [],
        'accepted_participations': []
    })

    all_participations = TeamParticipatesChallenge.objects.filter(
        team__participants__user=request.user
    )
    if all_participations.count() > 0 and team_pc is None:
        return redirect('accounts:panel', all_participations.first().id)
    for challenge_participation in all_participations:
        if not UserAcceptsTeamInChallenge.objects.filter(team=challenge_participation, user=request.user).exists():
            context['invitations'].append(challenge_participation)
        else:
            context['accepted_participations'].append(challenge_participation.team)
    return render(request, 'accounts/panel/team_management.html', context)


@payment_required
@login_required
def battle_history(request):
    team_pc = get_team_pc(request)
    if team_pc is None:
        return redirect_to_somewhere_better(request)
    context = get_shared_context(request)
    for item in context['menu_items']:
        if item['name'] == 'battle_history':
            item['active'] = True

    battles_page = request.GET.get('battles_page', 1)

    participation = team_pc
    if participation:
        participation_id = team_pc.id
        context.update({
            'participation': participation,
            'participation_id': participation_id,
        })

    if participation is not None and participation.challenge.competitions.filter(type='friendly').exists():
        context['form_challenge'] = ChallengeATeamForm(user=request.user, participation=participation)
        context['friendly_competition'] = participation.challenge.competitions.get(type='friendly')
        if participation is not None:
            context['challenge_teams'] = [team_part.team for team_part in
                                          TeamParticipatesChallenge.objects.filter(challenge=participation.challenge)]
            context.update({
                'battles_page': battles_page,
                'battle_history': Paginator(
                    Match.objects.filter(
                        Q(part1__object_id=participation_id) |
                        Q(part2__object_id=participation_id)).order_by('-id').filter(
                        competition__type='friendly'
                    ),
                    5).page(battles_page)
            })
    return render(request, 'accounts/panel/battle_history.html', context)

apps/accounts/views/profile.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from apps.accounts.forms.forms import UpdateProfileForm
from apps.accounts.models import Profile


class UpdateProfileView(LoginRequiredMixin, generic.UpdateView):
    form_class = UpdateProfileForm
    success_url = '/accounts/panel'
    template_name = 'accounts/profile/update_profile.html'
    model = Profile

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.id)

apps/accounts/views/team_required_and_finalized.py
def team_required_and_finalized(fn):
    pass
    def func(fn, *args, **kwargs):

        return func(fn, )

apps/accounts/templates/accounts/profile/login.html
{% extends 'base/base.html' %}

{% load static i18n %}

{% block container %}



    <form method="post" class="ui form">
        <h3 class="ui dividing header">{% trans 'Login' %}</h3>
        {% csrf_token %}

        <div class="field ">
            <label>{% trans 'Username' %}</label>
            {{ form.username }}
        </div>

        {% if form.username.errors %}
            <div class="ui message error">
                <strong>{{ form.username.errors }}</strong>
            </div>
        {% endif %}

        <div class="field ">
            <label>{% trans 'Password' %}</label>
            {{ form.password }}
        </div>


        <button type="submit" class="ui green button">{% trans 'Login' %}</button>
        <a href="{% url 'accounts:signup' %}" class="ui green button">{% trans 'Sign Up' %}</a>
        <p>
        <a class="ui blue link" href="{% url 'password_reset' %}">{% trans 'I forgot my password' %}</a>
        </p>
    </form>


{% endblock %}

apps/accounts/templates/accounts/profile/signup.html
{% extends 'base/base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Sign Up' %}{% endblock %}

{% block container %}
    <form method="post" class="ui form error">
        {% if form.non_field_errors|length %}
            <div class="ui red message">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        <h3 class="ui dividing header">{% trans 'SignUp Form' %}</h3>
        <div class="field required">
            <label>{% trans 'Username' %}</label>
            {{ form.username }}
        </div>
        <div class="ui message">
            <ul class="list">
                <p>{{ form.username.help_text|safe }}</p>
            </ul>
        </div>
        {% if form.username.errors %}
            <div class="ui message error">
                <strong>{{ form.username.errors }}</strong>
            </div>
        {% endif %}

        <div class="two fields">
            <div class="field required">
                <label>{% trans 'First Name' %}</label>
                {{ form.first_name }}
            </div>
            <div class="field required">
                <label>{% trans 'Last Name' %}</label>
                {{ form.last_name }}
            </div>
        </div>

        <div class="two fields">
            <div class="field required">
                <label>{% trans 'College/School' %}</label>
                {{ form.organization }}
            </div>
            <div class="field">
                <label>{% trans 'Phone Number' %}</label>
                {{ form.phone_number }}
            </div>
        </div>

        {% if form.organization.errors %}
            <div class="ui message error">
                <strong>{{ form.organization.errors }}</strong>
            </div>
        {% endif %}
        {% if form.phone_number.errors %}
            <div class="ui message error">
                <strong>{{ form.phone_number.errors }}</strong>
            </div>
        {% endif %}

        <div class="field required">
            <label>{% trans 'Email' %}</label>
            {{ form.email }}
        </div>
        {% if form.email.errors %}
            <div class="ui message error">
                <strong>{{ form.email.errors }}</strong>
            </div>
            <ol class="ui message error">
                {% for error in form.email.errors %}
                    <li>{{ error|escape }}</li>
                {% endfor %}
            </ol>
        {% endif %}

        <div class="field required">
            <label>{% trans 'Password' %}</label>
            {{ form.password1 }}
        </div>
        {#      <div class="ui message">#}
        {#          <p>{{ form.password1.help_text|safe }}</p>#}
        {#      </div>#}
        {% if form.password1.errors %}
            <ol class="ui message error">
                {% for error in form.password1.errors %}
                    <li>{{ error|escape }}</li>
                {% endfor %}
            </ol>
        {% endif %}

        <div class="field required">
            <label>{% trans 'Password Confirm' %}</label>
            {{ form.password2 }}
        </div>
        {% if form.password2.errors %}
            <ol class="ui message error">
                {% for error in form.password2.errors %}
                    {{ error|escape }}
                {% endfor %}
            </ol>
        {% endif %}

        <div class="field">
            {{ form.captcha }}
        </div>
        {% if form.captcha.errors %}
            <div class="ui message error">
                {{ form.captcha.errors }}
            </div>
        {% endif %}



        <button type="submit" class="ui green button">{% trans 'SignUp' %}</button>
    </form>
{% endblock %}

apps/accounts/templates/accounts/profile/update_profile.html
{% extends 'base/base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Sign Up' %}{% endblock %}

{% block container %}
  <h2>{% trans 'Sign up' %}</h2>
  <form method="post" class="ui form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="ui green button">{% trans 'Update' %}</button>
  </form>
{% endblock %}